project:
  type: book

book:
  title: "Data Scientist's Handbook: Mastering Inferential Statistics"
  author: "Brian Cervantes Alvarez"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: united
  pdf:
    documentclass: scrreprt



