project:
  type: book
  output-dir: docs

book:
  title: "Data Scientist's Handbook: Mastering Inferential Statistics"
  author: "Brian Cervantes Alvarez"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  page-navigation: true
  repo-branch: main

bibliography: references.bib

format:
  html:
    theme: united

editor: visual



