project:
  type: book

book:
  title: "A Data Scientist's Guide to Inferential Statistics"
  author: "Brian Cervantes Alvarez"
  date: "1/10/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: united
  pdf:
    documentclass: scrreprt



